spring:
  datasource:
    url: jdbc:mysql://localhost:3306/monitoring
    username: root
    password: yzc13569291231
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

  jackson:
    time-zone: Asia/Shanghai
  main:
    allow-circular-references: true

server:
  servlet:
    context-path: /
  port: 8848

